import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# API configuration
TUSHARE_TOKEN = os.getenv("TUSHARE_TOKEN")
TUSHARE_HTTP_URL = os.getenv("TUSHARE_HTTP_URL", "")
TUSHARE_REQUEST_DELAY = float(os.getenv("TUSHARE_REQUEST_DELAY", "0.5"))

# Output configuration
MASTER_DATA_DIR = os.path.join(BASE_DIR, "storage", "data_master")
BACKUP_DIR = os.path.join(BASE_DIR, "storage", "backups")
DAILY_BASICS_FILE = os.getenv("DAILY_BASICS_FILE", "每日基础数据.xlsx")
DAILY_BASICS_SHEET = os.getenv("DAILY_BASICS_SHEET", "Sheet1")
MARKET_SENTIMENT_FILE = os.getenv("MARKET_SENTIMENT_FILE", "近期市场情绪工作簿.xlsx")
MARKET_SENTIMENT_OVERVIEW_SHEET = os.getenv("MARKET_SENTIMENT_OVERVIEW_SHEET", "总览")
MARKET_SENTIMENT_MARKET_SHEET = os.getenv("MARKET_SENTIMENT_MARKET_SHEET", "总市场数据")
MARKET_SENTIMENT_HEIGHT_SHEET = os.getenv("MARKET_SENTIMENT_HEIGHT_SHEET", "高度观察")
MARKET_SENTIMENT_CHINEXT_SHEET = os.getenv("MARKET_SENTIMENT_CHINEXT_SHEET", "创业板专区")
MARKET_SENTIMENT_RECENT_FILE = os.getenv("MARKET_SENTIMENT_RECENT_FILE", "近期市场情绪工作簿.xlsx")
MARKET_SENTIMENT_HISTORY_FILE = os.getenv("MARKET_SENTIMENT_HISTORY_FILE", "历史市场情绪工作簿.xlsx")
MARKET_SENTIMENT_HISTORY_PREFIX = os.getenv("MARKET_SENTIMENT_HISTORY_PREFIX", "历史数据")
MARKET_SENTIMENT_SUPPLEMENT_PREFIX = os.getenv("MARKET_SENTIMENT_SUPPLEMENT_PREFIX", "补充数据")
MARKET_SENTIMENT_TEST_PREFIX = os.getenv("MARKET_SENTIMENT_TEST_PREFIX", "测试数据")

# Messaging configuration
FEISHU_BOT_WEBHOOK = os.getenv("FEISHU_BOT_WEBHOOK")
DINGDING_WEBHOOK = os.getenv("DINGDING_WEBHOOK", "")
WENCAI_COOKIE = os.getenv("WENCAI_COOKIE", "")
